### ISSUE TITLE
Home Assistant integration keeps searching

### ISSUE THREAD

**Issue by tjorim** [lkempf/casambi-bt#2]
Hi Lukas,

I was just trying out the HA integration you are building. Should it currently be in a working state? For me it just keeps searching as seen in the screenshot below.

![Screenshot_20221120-213740.png](https://user-images.githubusercontent.com/1294876/202924971-6101ee95-8ed6-4729-b825-06ad430e1817.png)

**Comment by lkempf** [comment]
I don't think it will work with HA version 2022.8 and upward until I have updated it to use the new Bluetooth backend. I roughly know how to update but won't be able to test it before Christmas so I haven't done so. I hope to get it done around the end of the year

**Comment by lkempf** [comment]
Since I was bored and was playing around with bluetooth in HA anyways I did the required modifications but I can't guarantee they actually work. If you would like to try it you would need to manually update the CasambiBt package HA is using to the latest commit and then update the integration. I might be able to fix trivial issues but for anything more complex I'll have to wait until I visit my parents.

**Comment by tjorim** [comment]
I was also playing around with it yesterday but have not a lot of experience building integrations from scratch 😅
Is it possible you still need to push v0.0.4 of this library to pypi (and bump the dependency in HA)?

```
This error originated from a custom integration.

Logger: custom_components.casambi.config_flow
Source: custom_components/casambi/config_flow.py:34
Integration: Casambi Bluetooth (documentation, issues)
First occurred: 6:20:17 AM (2 occurrences)
Last logged: 6:20:45 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/casambi/config_flow.py", line 103, in async_step_user
    info = await _validate_input(self.hass, user_input)
  File "/config/custom_components/casambi/config_flow.py", line 34, in _validate_input
    await casa.connect(bt_device, data[CONF_PASSWORD])
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_casambi.py", line 106, in connect
    networkId = await getNetworkIdFromUuid(addr, self._httpClient)
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_network.py", line 275, in getNetworkIdFromUuid
    getNetworkIdUrl = f"https://api.casambi.com/network/uuid/{mac.replace(':', '')}"
AttributeError: 'BLEDevice' object has no attribute 'replace'
```

**Comment by tjorim** [comment]
I manually set the integration requirement to main branch. Seeing the following erros when trying to add the light:

```
Logger: CasambiBt._client
Source: components/bluetooth/models.py:306
First occurred: 6:48:09 AM (1 occurrences)
Last logged: 6:48:09 AM

Failed to find client.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_client.py", line 100, in connect
    await self._gattClient.connect()
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/models.py", line 306, in connect
    return await super().connect(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 471, in connect
    return await self._backend.connect(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 98, in connect
    raise BleakError("Client is already connected")
bleak.exc.BleakError: Client is already connected
```

```
Logger: root
Source: runner.py:119
First occurred: 6:48:19 AM (1 occurrences)
Last logged: 6:48:19 AM

A message handler raised an exception: CasambiClient._on_disconnect() takes 1 positional argument but 2 were given. Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/dbus_fast/message_bus.py", line 778, in _process_message result = user_handler(msg) File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 852, in _parse_msg on_connected_changed(self_interface["Connected"]) File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 143, in on_connected_changed self._disconnected_callback(self) TypeError: CasambiClient._on_disconnect() takes 1 positional argument but 2 were given
```

```
This error originated from a custom integration.

Logger: CasambiBt._network
Source: custom_components/casambi/config_flow.py:34
Integration: Casambi Bluetooth (documentation, issues)
First occurred: 6:48:46 AM (2 occurrences)
Last logged: 6:48:58 AM

Getting network id returned 404
```

```
This error originated from a custom integration.

Logger: custom_components.casambi.config_flow
Source: custom_components/casambi/config_flow.py:34
Integration: Casambi Bluetooth (documentation, issues)
First occurred: 6:48:46 AM (2 occurrences)
Last logged: 6:48:58 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/casambi/config_flow.py", line 103, in async_step_user
    info = await _validate_input(self.hass, user_input)
  File "/config/custom_components/casambi/config_flow.py", line 34, in _validate_input
    await casa.connect(bt_device, data[CONF_PASSWORD])
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_casambi.py", line 116, in connect
    networkId = await getNetworkIdFromUuid(addr, self._httpClient)
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_network.py", line 281, in getNetworkIdFromUuid
    id = res.json()["id"]
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 743, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I manually connected to 2 bluetooth mac addresses I found with bluetooth scanner app.   The official Casambi app only finds 1 light so not sure which I should use.

**Comment by lkempf** [comment]
You'll have to keep using the version from github for now because I don't want to push a version to PyPi I haven't tested myself.
I think I fixed 3 of the issues you had.
However,
> Getting network id returned 404

does look to me like you're running into #1.

**Comment by tjorim** [comment]
Yes I verified that! At first they were open, now password protected. Still the same result. I see one device in the Casambi app but two with a bluetooth scanner on my phone:
![Screenshot_20221121-192343.png](https://user-images.githubusercontent.com/1294876/203131482-22662e8d-ba73-4400-a05f-10852d603bdb.png)

When connecting to the first MAC address in the list I get these errors:

```
This error originated from a custom integration.

Logger: CasambiBt._network
Source: custom_components/casambi/config_flow.py:34
Integration: Casambi Bluetooth (documentation, issues)
First occurred: 7:15:11 PM (1 occurrences)
Last logged: 7:15:11 PM

Getting network id returned 404
```

```
This error originated from a custom integration.

Logger: custom_components.casambi.config_flow
Source: custom_components/casambi/config_flow.py:34
Integration: Casambi Bluetooth (documentation, issues)
First occurred: 7:15:11 PM (1 occurrences)
Last logged: 7:15:11 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/casambi/config_flow.py", line 103, in async_step_user
    info = await _validate_input(self.hass, user_input)
  File "/config/custom_components/casambi/config_flow.py", line 34, in _validate_input
    await casa.connect(bt_device, data[CONF_PASSWORD])
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_casambi.py", line 116, in connect
    networkId = await getNetworkIdFromUuid(addr, self._httpClient)
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_network.py", line 281, in getNetworkIdFromUuid
    id = res.json()["id"]
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 743, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

When connecting to the second one in the list the following errors:

```
Logger: CasambiBt._client
Source: components/bluetooth/models.py:306
First occurred: 7:16:28 PM (1 occurrences)
Last logged: 7:16:28 PM

Failed to find client.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_client.py", line 100, in connect
    await self._gattClient.connect()
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/models.py", line 306, in connect
    return await super().connect(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 471, in connect
    return await self._backend.connect(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 98, in connect
    raise BleakError("Client is already connected")
bleak.exc.BleakError: Client is already connected
```

```
Logger: root
Source: runner.py:119
First occurred: 7:16:38 PM (1 occurrences)
Last logged: 7:16:38 PM

A message handler raised an exception: CasambiClient._on_disconnect() takes 1 positional argument but 2 were given. Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/dbus_fast/message_bus.py", line 778, in _process_message result = user_handler(msg) File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 852, in _parse_msg on_connected_changed(self_interface["Connected"]) File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 143, in on_connected_changed self._disconnected_callback(self) TypeError: CasambiClient._on_disconnect() takes 1 positional argument but 2 were given
```

Let me know if I van provide any additional details.

**Comment by tjorim** [comment]
I changed the firmware from Evolution to Classic. I still found the MAC that gave me a 404 error before, but the other one changed.

Name: CBU-PWM4 RGBW
Address: 27:62:6C:80:60:03
RSSI: -63 dBm
Last advertisement packet:
Raw data: 0x09FFC30327626C80600303024DFE02010605121C0024000E094342552D50574D342052474257

```
This error originated from a custom integration.

Logger: custom_components.casambi.config_flow
Source: custom_components/casambi/config_flow.py:34
Integration: Casambi Bluetooth (documentation, issues)
First occurred: 7:41:58 PM (1 occurrences)
Last logged: 7:41:58 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/casambi/config_flow.py", line 103, in async_step_user
    info = await _validate_input(self.hass, user_input)
  File "/config/custom_components/casambi/config_flow.py", line 34, in _validate_input
    await casa.connect(bt_device, data[CONF_PASSWORD])
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_casambi.py", line 122, in connect
    await self._casaNetwork.update()
  File "/usr/local/lib/python3.10/site-packages/CasambiBt/_network.py", line 148, in update
    keys = resJson["network"]["keyStore"]["keys"]
KeyError: 'keyStore'
```

**Comment by lkempf** [comment]
Thanks for being the tester for my changes.

> I changed the firmware from Evolution to Classic. I still found the MAC that gave me a 404 error before, but the other one changed.

The library should (only) work with Evolution because that's what what my parents are using iirc.

> When connecting to the second one in the list the following errors: [...]

These are both errors that should be fixed by aa2c585fef3521f42cc6beb4f720cd623ff9c772 so I guess your version just didn't get updated. I think the second try (with classic firmware) worked because it got updated in the meantime.

The code that is currently failing concerns communication with the Casambi API so this just means that you have found the correct mac. Could you try running demo.py in this repo instead of using trying to use the integration? This should work on any Bluetooth capable computer and doesn't require HA. Will this only discover the correct mac? If so my strategy of detecting the network controller should also work for your network. 

Running demo.py also outputs debug logging which would make it easier to find out what the issue is. **Warning:** The debug log might contain your network password in plaintext and you should censor that.

> Edit: I changed your integration to be used as a custom repo in HACS, code can be found [here](https://github.com/tjorim/casambi-ha).

Thanks. I'll probably use this as a template to create my own HACS compatible repo as soon as we get this issue resolved.

**Comment by lkempf** [comment]
I just tested the network code for my parents network and it works fine for me. I guess the network configuration returned for your network is slightly different and would need to look at that. The config should be fully dumped in the debug output in the message starting with `Network: `. I noticed that this contains a bunch of private information so you can also mail it to me (git@lukas-kempf.de) if you don't want to bother censoring everything. I think I have some more time to look at it later this evening but it might also take until tomorrow evening.

**Comment by CFenner** [comment]
I'm also interested in a working working HA integration. Currently I use https://github.com/hellqvio86/home_assistant_casambi but that uses the web api with a gateway. I would better like to use a local solution. Do you plan to contribute the HACS part back to this repo?

**Comment by lkempf** [comment]
Yes as soon as I have a version that I have could test with a recent version of HA.

**Comment by lkempf** [comment]
I now have my own HACS compatible integration under https://github.com/lkempf/casambi-bt-hass and it works quite well for my parents network.

**Comment by CFenner** [comment]
How do you setup the integration? Luminaires are discovered but what do I need to fill in as password? Network password and api key do not work.

**Comment by lkempf** [comment]
Did you check that your network config matches the one in the readme? If my library doesn't like it you should get an authentication error otherwise it will be an unknown error.

**Comment by sMauldaeschle** [comment]
Great effort and congrats for this step! Does the integration conflict with hellqvio86's home_assistant_casambi integration or can it be installed and used in parallel?

**Comment by CFenner** [comment]
Unfortunately it uses the same domain and folder in custom components.

**Comment by lkempf** [comment]
@sMauldaeschle the domain and folder collisions have been resolved (thanks to @CFenner). In theory the two integrations should work at the same time now but I have no gateway to test this. However I know that my integration and the casambi app can be used at the same time.

I'm also closing this issue since the original issue has been resolved and this conversation isn't really on topic any more.
